from pathlib import Path
p=Path('public/app.js')
s=p.read_text(encoding='utf-8')
old="""  function renderGuiaPedagogico(){ return docShell('Guia Pedagógico do Professor',`<h4>Organização didática</h4><p>A disciplina está estruturada em cinco módulos progressivos. O estudante conclui o ciclo avaliativo após realizar as cinco listas, o Quiz e a Recuperação obrigatória; o avanço ocorre somente após a liberação individual do professor.</p><h4>Estrutura de cada módulo</h4><ul><li>Conteúdo teórico e exemplos;</li><li>5 listas autocorrigidas de 10 questões;</li><li>Quiz avaliativo autocorrigido;</li><li>Recuperação obrigatória e autocorrigida;</li><li>Nota do Módulo calculada automaticamente.</li></ul><h4>Avaliação</h4><p>Os 5 exercícios e o Quiz têm o mesmo peso. A Recuperação não é uma 7ª nota: substitui individualmente todas as notas inferiores entre essas 6 atividades. Entrega após o prazo original, quando autorizada, recebe desconto automático de 2,0 pontos.</p><h4>Intervenção pedagógica</h4><p>Use Notas da Turma e Relatórios para acompanhar o desempenho detalhado; Pendências para liberar individualmente o avanço dos alunos, regularizar cadastros e responder mensagens; Auditoria para rastreabilidade e Suporte para dúvidas e ocorrências.</p><h4>Boas práticas</h4><p>Defina os prazos antes da abertura da turma, acompanhe o progresso e as notas por atividade, trate as pendências operacionais e gere backup periódico.</p>`); }"""
new="""  const GUIA_PEDAGOGICO_MATERIAIS = {
    metodologia:[
      {titulo:'Metodologia de Ensino-Aprendizagem — Contabilidade Avançada',descricao:'Referencial metodológico da disciplina: sala de aula invertida, aprendizagem baseada em problemas, grupos operativos, prática guiada e abordagem inclusiva.',arquivo:'/guia-pedagogico/metodologia/metodologia-contabilidade-avancada.pdf'},
      {titulo:'Orientações de Avaliação e Recuperação Paralela',descricao:'Critérios de acompanhamento, avaliação automática, recuperação paralela, pontualidade e intervenção pedagógica.',arquivo:'/guia-pedagogico/metodologia/avaliacao-recuperacao-paralela.pdf'}
    ],
    slides: MODULES.map(m=>({titulo:`Módulo ${m.num} — ${m.title}`,descricao:`Slides de apoio exclusivos do Professor para o Módulo ${m.num}.`,arquivo:`/guia-pedagogico/slides/modulo-${m.num}.pdf`}))
  };
  function guiaMaterialCard(item,tipo){
    return `<div class="card-box"><div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap"><div style="flex:1;min-width:240px"><span class="status-badge info">${tipo==='metodologia'?'PDF metodológico':'Slides do Professor'}</span><h4 style="margin:10px 0 6px">${esc(item.titulo)}</h4><p class="desc">${esc(item.descricao)}</p></div><a class="btn-outline" href="${esc(item.arquivo)}" target="_blank" rel="noopener" data-guia-material>Visualizar PDF</a></div></div>`;
  }
  function renderGuiaPedagogico(){
    if(!state.user||state.user.role!=='professor') return `<div class="empty-state">Área exclusiva do Professor.</div>`;
    return `<div class="section-title">Guia Pedagógico do Professor</div><div class="note"><b>Área exclusiva do Professor.</b> Reúne orientações metodológicas e slides de apoio da disciplina Contabilidade Avançada. Os materiais pedagógicos desta área não aparecem no ambiente do Aluno.</div><div class="card-box"><h4>Organização didática</h4><p>A disciplina está estruturada em cinco módulos progressivos. O estudante realiza as cinco listas, o Quiz e a Recuperação obrigatória; o avanço depende da liberação individual do professor.</p><p>Use os documentos metodológicos como referência para planejamento, condução das aulas, avaliação e recuperação. Os slides são materiais de apoio ao desenvolvimento presencial dos conteúdos.</p></div><div class="section-title">PDFs de Metodologia</div>${GUIA_PEDAGOGICO_MATERIAIS.metodologia.map(x=>guiaMaterialCard(x,'metodologia')).join('')}<div class="section-title">Slides por Módulo</div>${GUIA_PEDAGOGICO_MATERIAIS.slides.map(x=>guiaMaterialCard(x,'slides')).join('')}<div class="note">Os botões ficam vinculados à estrutura padronizada <b>06-guia-pedagogico</b>. Caso um PDF ainda não tenha sido publicado, o material deve ser incluído na pasta correspondente do projeto mantendo o mesmo nome de arquivo.</div>`;
  }"""
if old not in s: raise SystemExit('guia original não encontrado')
s=s.replace(old,new)
s=s.replace('<h4>6. Pendências, relatórios e suporte</h4>', '<h4>6. Guia Pedagógico</h4><p>Área exclusiva do Professor com PDFs de metodologia e slides de apoio por módulo. Os materiais ficam separados do ambiente do Aluno e seguem a estrutura padronizada do projeto.</p><h4>7. Pendências, relatórios e suporte</h4>')
s=s.replace('<h4>Suporte</h4>\n    <p>No menu "Suporte" há duas áreas:', '<h4>Guia Pedagógico</h4><p>O menu "Guia Pedagógico" é exclusivo do Professor e reúne PDFs de metodologia e slides de apoio por módulo. Esses materiais não são exibidos ao Aluno.</p>\n    <h4>Suporte</h4>\n    <p>No menu "Suporte" há duas áreas:')
p.write_text(s,encoding='utf-8')
